CREATE TABLE sensordata (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    sensor VARCHAR(30) NOT NULL,
    wert FLOAT,
    zeit TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)

-- INSERT INTO `sensordata`(`sensor`, `wert`) VALUES ("huhu", 99)


CREATE TABLE receiveddata (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    msg VARCHAR(100) NOT NULL
)