CREATE TABLE `users` (`id` INT NOT NULL AUTO_INCREMENT , `fingerprintHex` TEXT NOT NULL , `zeit` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , `name` VARCHAR(200), `email` VARCHAR(200), `tel` VARCHAR(200), PRIMARY KEY (`id`)) ENGINE = InnoDB;


CREATE TABLE `history` (`id` INT NOT NULL AUTO_INCREMENT , `user_id` INT NOT NULL , `zeit` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;